name: $(BuildID)-$(Build.SourceBranchName)

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildAndPushDockerImage
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'rtuitlab connection by admin'
        repository: 'rtuitlab/webvrshoot'
        command: 'buildAndPush'
        Dockerfile: 'deploy/Dockerfile'
        buildContext: 
        tags: |
          $(Build.BuildId)
          latest
